### ISSUE TITLE
[提问]: 录制快手时录了一个小时，但是只有十几分钟,再次录制检测不到直播间。

### ISSUE THREAD

**Issue by SiLeDeAnSha** [hr3lxphr6j/bililive-go#515] opened 2023-08-06 15:45 UTC
### 程序版本

0.7.15

### 所使用的 config 文件的内容

使用的更多姿势里的config内容
rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 15
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.panda.tv/10300
  is_listening: true
  quality: 0
- url: https://live.kuaishou.com/u/3xrhq4ez766witc
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 1h0m0s
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
timeout_in_us: 60000000

### 程序 log

time="2023-08-06 23:43:53" level=info msg="BiliLive-go Version: v0.7.15 Link Start"
time="2023-08-06 23:43:53" level=debug msg="config path: D:\\bililive-go\\config.yml."
time="2023-08-06 23:43:53" level=debug msg="other flags have been ignored."
time="2023-08-06 23:43:53" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.15 BuildTime:2023-07-30_08:24:00 GitHash:346816ab8d409e51f3b61326c5692eac1ee437c8 Pid:6484 Platform:windows/amd64 GoVersion:go1.19.11}"
time="2023-08-06 23:43:53" level=debug msg="&{File:D:\\bililive-go\\config.yml RPC:{Enable:true Bind:127.0.0.1:8080} Debug:true Interval:15 OutPutPath:./ FfmpegPath: Log:{OutPutFolder:./ SaveLastLog:true SaveEveryLog:false} Feature:{UseNativeFlvParser:false RemoveSymbolOtherCharacter:false} LiveRooms:[{Url:https://www.panda.tv/10300 IsListening:true LiveId: Quality:0} {Url:https://live.kuaishou.com/u/3xrhq4ez766witc IsListening:true LiveId: Quality:0}] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:1h0m0s} Cookies:map[live.kuaishou.com:clientid=3; did=web_7880d5ae7d65751bae51779e96003661; client_key=65890b29; kpn=GAME_ZONE; _did=web_54012635975105D3; did=web_fcb267cb77f3a5b7646d4c95c3f8038f4093; userId=131983642; kuaishou.live.web_st=ChRrdWFpc2hvdS5saXZlLndlYi5zdBKQAVC7K2VnA0Ir7xlf5h0RJ8XCEkmeYDDJ8JiPxWu1UAn17C39MclixSWrfDZL7GLQANKvncjNqe6Zk8XI7cwZH7uP2PdrsUIEeFHxXHGRINSbTpcP14Ya0W_YDIXpSwfBPtU_pSOKAGqnUYWP8dtlprxtQoFU-wf6BjfwNA4OxMivrvmbAiurynzUPm82hXaH8RoS6sq82CFeRTS8ib9b9Rc9R-7BIiCherLmrixuLiqzwKxADi4qVCLsQIo7nzf2Nnc8nNIDFigFMAE; kuaishou.live.web_ph=620c21445218c2392a77d42c606f85bb1f3c; userId=131983642; kuaishou.live.bfb1s=ac5f27b3b62895859c4c1622f49856a4] OnRecordFinished:{ConvertToMp4:true DeleteFlvAfterConvert:true} TimeoutInUs:60000000 liveRoomIndexCache:map[https://live.kuaishou.com/u/3xrhq4ez766witc:1 https://www.panda.tv/10300:0]}"
time="2023-08-06 23:43:53" level=error msg="not support this url" url="&{https://www.panda.tv/10300 true  0}"
time="2023-08-06 23:43:54" level=info msg="Server start at 127.0.0.1:8080"
time="2023-08-06 23:43:58" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="127.0.0.1:62296"
time="2023-08-06 23:43:58" level=debug msg="Http Request" Method=GET Path=/static/css/2.5b1f1a89.chunk.css RemoteAddr="127.0.0.1:62296"
time="2023-08-06 23:43:58" level=debug msg="Http Request" Method=GET Path=/static/css/main.6220e936.chunk.css RemoteAddr="127.0.0.1:62297"
time="2023-08-06 23:43:58" level=debug msg="Http Request" Method=GET Path=/static/js/2.09e56847.chunk.js RemoteAddr="127.0.0.1:62298"
time="2023-08-06 23:43:58" level=debug msg="Http Request" Method=GET Path=/static/js/main.c077553f.chunk.js RemoteAddr="127.0.0.1:62299"
time="2023-08-06 23:43:59" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="127.0.0.1:62298"
time="2023-08-06 23:43:59" level=debug msg="Http Request" Method=GET Path=/manifest.json RemoteAddr="127.0.0.1:62302"
time="2023-08-06 23:43:59" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="127.0.0.1:62298"
time="2023-08-06 23:44:00" level=debug msg="Http Request" Method=DELETE Path=/api/lives/5caedfee4077c394ebfea052c542ccc1 RemoteAddr="127.0.0.1:62298"
time="2023-08-06 23:44:00" level=debug msg="Http Request" Method=PUT Path=/api/config RemoteAddr="127.0.0.1:62298"
time="2023-08-06 23:44:00" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="127.0.0.1:62299"
time="2023-08-06 23:44:02" level=debug msg="Http Request" Method=POST Path=/api/lives RemoteAddr="127.0.0.1:62299"
time="2023-08-06 23:44:02" level=debug msg="Http Request" Method=PUT Path=/api/config RemoteAddr="127.0.0.1:62299"
time="2023-08-06 23:44:02" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="127.0.0.1:62299"

### 自由描述

重新录制就检测不到直播间主播和名称了录制斗鱼其他平台没有问题，请问怎么解决呢？

**Comment by kira1928** [comment] 2023-08-07 05:15
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/447

**Closed by kira1928** 2023-08-07 05:15 UTC
Labels: question

**Comment by SiLeDeAnSha** [comment] 2023-08-07 11:33
> 
config里是像这样写吗
cookies:
  live.kuaishou.com:（这里是cookie）

**Comment by SiLeDeAnSha** [comment] 2023-08-07 11:36
> 的副本 #447
config里是像这样写吗
cookies： live.kuaishou.com： （这里是cookie）

**Comment by kira1928** [comment] 2023-08-07 18:39
快手的 cookie 域名是对的，但格式要符合 yaml 语法。
可以看 README 里 cookie [在 config.yml 中的设置方法](https://github.com/hr3lxphr6j/bililive-go#cookie-%E5%9C%A8-configyml-%E4%B8%AD%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95) 部分的示例。尤其要注意快手域名后面的冒号和它后面的 cookie 字符串之间有一个空格。已经有很多人因为没写那个空格导致语法错误了。
