### ISSUE TITLE
抖音录制突然中断

### ISSUE THREAD

**Issue by linuxtechnology** [hr3lxphr6j/bililive-go#624] opened 2023-12-25 08:52 UTC
### 程序版本

v0.7.20

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /Users/*/Movies/录像/
ffmpeg_path: # 如果此项为空，就自动在环境变量里寻找
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
live_rooms:
# qulity参数目前仅B站启用，默认为0
# (B站)0代表原画PRO(HEVC)优先, 其他数值为原画(AVC)
# 原画PRO会保存为.ts文件, 原画为.flv
# HEVC相比AVC体积更小, 减少35%体积, 画质相当, 但是B站转码有时候会崩
live_rooms:
  - url: https://live.douyin.com/1
    is_listening: true
    out_put_path: /Users/*/Movies/录像/  # 特定直播间的输出路径
 
  - url: https://live.douyin.com/2
    is_listening: true

    out_put_path: /Users/*/Movies/录像/  # 特定直播间的输出路径
 
  - url: https://live.douyin.com/3
    is_listening: true

    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径
 
  - url: https://live.douyin.com/4
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径
 
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径
 
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*.*  # 特定直播间的输出路径
 
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径  

 
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径  
 
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径
 
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径
 
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径 
 
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径     
  
              
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径 

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径  
  
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*
  
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*
#############
  
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径
  
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 特定直播间的输出路径
  
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*  # 另一个直播间的输出路径
  
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*'s  # 特定直播间的输出路径

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/* # 特定直播间的输出路径

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*
  
  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*-
  

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*    # 特定直播间的输出路径

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*    # 特定直播间的输出路径

  - url: https://live.douyin.com/*
    is_listening: true
   
    out_put_path: /Users/*/Movies/录像/*    # 特定直播间的输出路径
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  # 仅在 use_native_flv_parser=false 时生效
  # 单位为字节 (byte)
  # 有效值为正数，默认值 0 为无效
  # 负数为非法值，程序会输出 log 提醒，并无视所设定的数值
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
#  当 custom_commandline 的值 不为空时，convert_to_mp4 的值会被无视，
#  而是在录制结束后直接执行 custom_commandline 中的命令。
#  在 custom_commandline 执行结束后，程序还会继续查看 delete_flv_after_convert 的值，
#  来判断是否需要删除原始 flv 文件。
#  以下是一个在录制结束后将 flv 视频转换为同名 mp4 视频的示例：
#  custom_commandline: '{{ .Ffmpeg }} -hide_banner -i "{{ .FileName }}" -c copy "{{ .FileName | trimSuffix (.FileName | ext)}}.mp4"'
  custom_commandline: '{{ .Ffmpeg }} -hide_banner -i "{{ .FileName }}" -c copy "{{ .FileName | trimSuffix (.FileName | ext)}}.mp4"'
timeout_in_us: 60000000

### 程序 log

panic: runtime error: index out of range [1] with length 1

goroutine 87 [running]:
github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).tryRecord(0xc000126120, {0x202b198, 0xc000341cb0})
	/home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:204 +0x1ab6
github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).run(0xc000126120, {0x202b198, 0xc000341cb0})
	/home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:241 +0x39
created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).Start
	/home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:265 +0xc5

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[程序完成]

### 自由描述

添加了很多个抖音直播间，但是在录制的过程中会突然中断。
bililive-go报错提示Go 语言程序时遇到了运行时错误panic 您看下代码循环语句。谢谢

**Comment by Aric-Sun** [comment] 2023-12-26 15:44
换成https://live.douyin.com/`抖音号` 试试看

**Comment by kira1928** [comment] 2023-12-27 17:33
正在修复。
https://github.com/hr3lxphr6j/bililive-go/issues/543

**Comment by kira1928** [comment] 2023-12-28 05:19
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/621

**Closed by kira1928** 2023-12-28 05:19 UTC
Labels: bug
