### ISSUE TITLE
twitch平台无法录制一直初始化

### ISSUE THREAD

**Issue by chaogemars** [hr3lxphr6j/bililive-go#761] opened 2024-07-08 04:41 UTC
### 程序版本

0.7.30

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.bilibili.com/32341096?broadcast_type=0&is_room_feed=1&spm_id_from=333.999.to_liveroom.0.click&live_from=86002
  is_listening: true
  quality: 0
  audio_only: false
- url: https://live.bilibili.com/7150448?broadcast_type=0&is_room_feed=1&spm_id_from=333.999.to_liveroom.0.click&live_from=86002
  is_listening: true
  quality: 0
  audio_only: false
- url: https://www.twitch.tv/bps1016
  is_listening: true
  quality: 0
  audio_only: false
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log

![屏幕截图 2024-07-08 124040](https://github.com/hr3lxphr6j/bililive-go/assets/53162634/1264c0a0-5a61-4ab9-884d-84db38ef087e)

### 自由描述

无法录制一直显示初始化

**Comment by kira1928** [comment] 2024-07-09 14:26
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/188

**Closed by kira1928** 2024-07-09 14:26 UTC
Labels: bug
