### ISSUE TITLE
希望添加bigo live直播支持

### ISSUE THREAD

**Issue by dai1400** [hr3lxphr6j/bililive-go#519] opened 2023-08-13 04:17 UTC
### 目标网站任意直播间的示例 url，精确到具体直播间

https://www.bigo.tv/cn/681383794

**Comment by justdoiting** [comment] 2023-10-30 09:56
import requests
import time
import os
import threading
import random
import datetime

class Bigo:
    def __init__(self, rid):
        self.rid = rid
        self.flag = False
        self.run = False

    def get_real_url(self):
        with requests.Session() as s:
            url = f'https://ta.bigo.tv/official_website/studio/getInternalStudioInfo'
            res = s.post(url, data={'siteId': self.rid}).json()
            hls_src = res['data']['hls_src']
            play_url = hls_src if hls_src else None
            return play_url

    def checkLive(self):
        try:
            u = self.get_real_url()
            if u:
                print('正在直播！',u)
                self.flag = True
            else:
                print('未直播')
                self.flag = False
                time.sleep(random.randint(10,30))
        except Exception as e:
            print('Exception：', e)
            self.flag = False

    def ffmpegDown(self):
        url = self.get_real_url()
        print('直播源：',url)
        filename = datetime.datetime.today()
        filename = filename.strftime('%Y%m%d%H%M%S')
        filename = filename + '.mp4'
        print(filename)
        file_path = "./"
        print('ffmpeg -i {} -c copy {}'.format(url, os.path.join(file_path,filename)))
        os.system('ffmpeg -i {} -c copy {}'.format(url, os.path.join(file_path,filename)))

    def recording(self):
        while True:
            print("-------recoding-------")
            time.sleep(5)
            if self.flag == True and self.run == False:
                print("---开始录制")
                self.ffmpegDown()
                self.run = True
            elif self.flag == True and self.run == True:
                print("---正在录制")
            else:
                print('---未直播')
                self.run = False

if __name__ == '__main__':
    r = input('输入bigo直播房间号：\n')
    site = Bigo(r)
    change = threading.Thread(target=site.checkLive)
    ffm = threading.Thread(target=site.recording)
    # 开始运行程序
    change.start()
    ffm.start()

**Comment by kira1928** [comment] 2023-10-30 15:37
Duplicate of #258

**Closed by kira1928** 2023-10-30 15:37 UTC
Labels: new site request
