### ISSUE TITLE
Douyin recording is not in original resolution

### ISSUE THREAD

**Issue by AvrilL161** [hr3lxphr6j/bililive-go#590] opened 2023-11-04 14:41 UTC
### 程序版本

0.7.19

### 所使用的 config 文件的内容
```
rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: true
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
live_rooms:
# qulity参数目前仅B站启用，默认为0
# (B站)0代表原画PRO(HEVC)优先, 其他数值为原画(AVC)
# 原画PRO会保存为.ts文件, 原画为.flv
# HEVC相比AVC体积更小, 减少35%体积, 画质相当, 但是B站转码有时候会崩
- url: https://live.douyin.com/Fengtimo1219
  is_listening: true
  quality: 0
- url: https://live.douyin.com/hanhantimo
  is_listening: true
  quality: 0
- url: https://live.douyin.com/5893162289
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  # 仅在 use_native_flv_parser=false 时生效
  # 单位为字节 (byte)
  # 有效值为正数，默认值 0 为无效
  # 负数为非法值，程序会输出 log 提醒，并无视所设定的数值
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
#  当 custom_commandline 的值 不为空时，convert_to_mp4 的值会被无视，
#  而是在录制结束后直接执行 custom_commandline 中的命令。
#  在 custom_commandline 执行结束后，程序还会继续查看 delete_flv_after_convert 的值，
#  来判断是否需要删除原始 flv 文件。
#  以下是一个在录制结束后将 flv 视频转换为同名 mp4 视频的示例：
#  custom_commandline: '{{ .Ffmpeg }} -hide_banner -i "{{ .FileName }}" -c copy "{{ .FileName | trimSuffix (.FileName | ext)}}.mp4"'
  custom_commandline: ""
timeout_in_us: 60000000
```
### 程序 log

time="2023-11-04 17:20:06" level=info msg="BiliLive-go Version: v0.7.19 Link Start"
time="2023-11-04 17:20:06" level=debug msg="config path: E:\\Timo\\down\\OBS\\concat\\test\\blg\\config.yml."
time="2023-11-04 17:20:06" level=debug msg="other flags have been ignored."
time="2023-11-04 17:20:06" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.19 BuildTime:2023-11-04_12:21:20 GitHash:1d70c5526984402e7b4849c2356dd52ee9b26f51 Pid:20304 Platform:windows/amd64 GoVersion:go1.19.13}"
time="2023-11-04 17:20:06" level=debug msg="&{File:E:\\Timo\\down\\OBS\\concat\\test\\blg\\config.yml RPC:{Enable:true Bind:127.0.0.1:8080} Debug:true Interval:20 OutPutPath:./ FfmpegPath: Log:{OutPutFolder:./ SaveLastLog:true SaveEveryLog:false} Feature:{UseNativeFlvParser:false RemoveSymbolOtherCharacter:false} LiveRooms:[{Url:https://live.douyin.com/Fengtimo1219 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/hanhantimo IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/5893162289 IsListening:true LiveId: Quality:0}] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s MaxFileSize:0} Cookies:map[] OnRecordFinished:{ConvertToMp4:false DeleteFlvAfterConvert:false CustomCommandline:} TimeoutInUs:60000000 liveRoomIndexCache:map[https://live.douyin.com/5893162289:2 https://live.douyin.com/Fengtimo1219:0 https://live.douyin.com/hanhantimo:1]}"
time="2023-11-04 17:20:09" level=info msg="Server start at 127.0.0.1:8080"
time="2023-11-04 17:20:21" level=info msg="Live Start" host="疯狂小杨哥" room="双十一美妆节"
time="2023-11-04 17:20:21" level=info msg="Record Start" host="疯狂小杨哥" room="双十一美妆节"
time="2023-11-04 17:20:21" level=debug msg="Start ParseLiveStream(http://pull-flv-f1.douyincdn.com/stagereplay/stream-7297605735724321573_hd.flv, 抖音\\疯狂小杨哥\\[2023-11-04 17-20-21][疯狂小杨哥][双十一美妆节].flv)" host="疯狂小杨哥" room="双十一美妆节"
time="2023-11-04 17:20:42" level=info msg="Server close"
time="2023-11-04 17:20:42" level=info msg="Record End" host="疯狂小杨哥" room="双十一美妆节"
time="2023-11-04 17:20:42" level=info msg="Bye~"

### 自由描述

I tested the new version.
room https://live.douyin.com/5893162289
recorded in a resolution of 720x1280 (original 1088x1920).
I tried removing the "quality" line in the configuration file.
I restarted the application three times, and each time the recording occurs in a resolution of 720x1280.
Another application records 1088x1920.
![2023-11-04_17-39-16](https://github.com/hr3lxphr6j/bililive-go/assets/29428522/b1be0448-14d8-4f4e-aca7-e464ef205141)
![2023-11-04_17-39-58](https://github.com/hr3lxphr6j/bililive-go/assets/29428522/70a486fe-999d-4929-879c-d2f4f05800c3)

**Comment by kira1928** [comment] 2023-11-05 13:54
Duplicate of #563

**Closed by kira1928** 2023-11-05 13:54 UTC
Labels: bug
