### ISSUE TITLE
twitch无法录制，一直显示监控中，初始化，没有显示主播名称和直播平台

### ISSUE THREAD

**Issue by Oururis** [hr3lxphr6j/bililive-go#616] opened 2023-12-18 10:35 UTC
### 程序版本

0.7.20

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: F:/Tool/ffmpeg/bin
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.twitch.tv/mira
  is_listening: true
  quality: 0
- url: https://live.bilibili.com/27610155
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies:
  www.twitch.tv: __ac_nonce=re15****mjofzokk**************
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log
time="2023-12-18 18:35:09" level=info msg="BiliLive-go Version: v0.7.20 Link Start"
time="2023-12-18 18:35:14" level=info msg="Server start at :8080"
time="2023-12-18 18:35:20" level=info msg="Live Start" host="斤斤的甜芋泥" room="整容失败 转播皮套"
time="2023-12-18 18:35:20" level=info msg="Record Start" host="斤斤的甜芋泥" room="整容失败 转播皮套"

_No response_

### 自由描述

B站随便找了个主播，马上就开始录制了，录了一阵之后命令窗口消失，网页报错，再次启动无果，显示time="2023-12-18 18:35:09" level=info msg="BiliLive-go Version: v0.7.20 Link Start"

随后再次自动关闭，产生了录制文件夹，但文件夹内空

**Comment by Oururis** [comment] 2023-12-18 10:41
将配置文件中ffmpeg路径删除后似乎又恢复了正常，将ffmpeg添加到环境变量后再次启动，正常，B站录制成功

**Comment by kira1928** [comment] 2023-12-27 17:38
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/188

**Closed by kira1928** 2023-12-27 17:38 UTC
Labels: bug
