### ISSUE TITLE
win端程序运行一段时间出现以下错误信息

### ISSUE THREAD

**Issue by zxr10-ha** [hr3lxphr6j/bililive-go#532] opened 2023-08-24 21:29 UTC
### 程序版本

0.7.15

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 120
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
out_put_tmpl: '{{ .Live.GetPlatformCNName }}/{{ .HostName | filenameFilter }}/{{ .HostName | filenameFilter }}_{{ now | date "2006-01-02_15-04-05"}}.flv'
video_split_strategies:
  on_room_name_changed: false
  max_duration: 5h0m0s
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
timeout_in_us: 60000000

### 程序 log

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x54 pc=0x1450c6a]

goroutine 52861 [running]:
github.com/hr3lxphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).Stop.func1()
        /home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:162 +0x1a
sync.(*Once).doSlow(0x129db6f0, 0x1355af34)
        /opt/hostedtoolcache/go/1.19.11/x64/src/sync/once.go:74 +0xb3
sync.(*Once).Do(0x129db6f0, 0x1355af34)
        /opt/hostedtoolcache/go/1.19.11/x64/src/sync/once.go:65 +0x3f
github.com/hr3lxphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).Stop(0x13056ae0)
        /home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:161 +0x4a
github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).Close(0x12a26000)
        /home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:232 +0x76
github.com/hr3lxphr6j/bililive-go/src/recorders.(*manager).RemoveRecorder(0x12d76720, {0x1e6ccc0, 0x1298b830}, {0x129ce520, 0x20})
        /home/runner/work/bililive-go/bililive-go/src/recorders/manager.go:148 +0xb3
github.com/hr3lxphr6j/bililive-go/src/recorders.(*manager).registryListener.func3(0x131fe1d0)
        /home/runner/work/bililive-go/bililive-go/src/recorders/manager.go:69 +0xd7
github.com/hr3lxphr6j/bililive-go/src/pkg/events.(*dispatcher).DispatchEvent.func1()
        /home/runner/work/bililive-go/bililive-go/src/pkg/events/dispatcher.go:96 +0x40
created by github.com/hr3lxphr6j/bililive-go/src/pkg/events.(*dispatcher).DispatchEvent
        /home/runner/work/bililive-go/bililive-go/src/pkg/events/dispatcher.go:94 +0x1ea

### 自由描述

win端程序，运行一段时间就会出现上面的错误信息（出现频率不固定，有时候连续运行两天也不会出现错误，有时候一天出现多次。最近一段时间，出现频率有所增加），出现错误信息时，正在录制的直播间会继续录制，但是新开播的直播间不会录制，并且web前端页面（http://127.0.0.1:8080/#/）打不开。

**Comment by kira1928** [comment] 2023-08-27 14:18
这是一个多线程竞争bug，一般出现在录制结束时。是原作者时期就有的bug。好像比较难解决，就一直搁置到现在了。。
关于他的讨论我想集中在原始 issue 里，等过两天我找找那个 issue，找到后会把那个 issue 链接发在这边，然后这个 issue 我就关闭了。因为是重复的已知bug。

**Comment by zxr10-ha** [comment] 2023-08-27 14:57
好的，感谢大佬解答。

**Comment by kira1928** [comment] 2023-08-28 04:19
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/204

**Closed by kira1928** 2023-08-28 04:19 UTC
Labels: bug
